server {
    server_name hexadella.space www.hexadella.space;

    root /var/www/hexadella.space;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/hexadella.space/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hexadella.space/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.hexadella.space) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = hexadella.space) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name hexadella.space www.hexadella.space;
    return 404; # managed by Certbot
}
